package com.example.palmistry.security

import android.util.Base64
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec
import javax.crypto.spec.SecretKeySpec
import javax.inject.Inject
import javax.inject.Singleton

/**
 * AES-256-GCM Encryption Utility
 * - Encrypts JSON payload before sending to server
 * - Decrypts server response
 * - GCM mode ensures both confidentiality + integrity
 */
@Singleton
class EncryptionUtil @Inject constructor() {

    companion object {
        private const val AES_KEY_SIZE = 256
        private const val GCM_IV_LENGTH = 12   // 96 bits recommended for GCM
        private const val GCM_TAG_LENGTH = 128  // 128 bits authentication tag
        private const val ALGORITHM = "AES/GCM/NoPadding"
    }

    /**
     * Generates a new random AES-256 secret key.
     * In production: store this key securely using Android Keystore.
     */
    fun generateKey(): SecretKey {
        val keyGen = KeyGenerator.getInstance("AES")
        keyGen.init(AES_KEY_SIZE)
        return keyGen.generateKey()
    }

    /**
     * Encrypts plaintext string using AES-256-GCM.
     * Output format: Base64(IV + CipherText)
     */
    fun encrypt(plaintext: String, secretKey: SecretKey): String {
        val cipher = Cipher.getInstance(ALGORITHM)
        cipher.init(Cipher.ENCRYPT_MODE, secretKey)
        val iv = cipher.iv  // Random IV generated by cipher
        val cipherText = cipher.doFinal(plaintext.toByteArray(Charsets.UTF_8))

        // Prepend IV to ciphertext for decryption later
        val ivAndCipherText = iv + cipherText
        return Base64.encodeToString(ivAndCipherText, Base64.NO_WRAP)
    }

    /**
     * Decrypts Base64(IV + CipherText) using AES-256-GCM.
     * Throws exception if data has been tampered with (GCM integrity check).
     */
    fun decrypt(encryptedData: String, secretKey: SecretKey): String {
        val ivAndCipherText = Base64.decode(encryptedData, Base64.NO_WRAP)
        val iv = ivAndCipherText.copyOfRange(0, GCM_IV_LENGTH)
        val cipherText = ivAndCipherText.copyOfRange(GCM_IV_LENGTH, ivAndCipherText.size)

        val cipher = Cipher.getInstance(ALGORITHM)
        val spec = GCMParameterSpec(GCM_TAG_LENGTH, iv)
        cipher.init(Cipher.DECRYPT_MODE, secretKey, spec)
        val plainText = cipher.doFinal(cipherText)
        return String(plainText, Charsets.UTF_8)
    }

    /**
     * Converts a raw Base64-encoded key string back to SecretKey.
     * Use this when retrieving a stored key.
     */
    fun keyFromBase64(base64Key: String): SecretKey {
        val keyBytes = Base64.decode(base64Key, Base64.NO_WRAP)
        return SecretKeySpec(keyBytes, "AES")
    }

    /**
     * Encodes a SecretKey to Base64 string for storage.
     */
    fun keyToBase64(secretKey: SecretKey): String {
        return Base64.encodeToString(secretKey.encoded, Base64.NO_WRAP)
    }
}
